name: Test
on: [push]
jobs:
  bash-completions-checker:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Run tests
        run: |
          bash tests/test-bash-completions-getter.sh

